(define (problem paracetamol)
	(:domain painkiller)
	(:init
		(safe-to-consume)
		(min-check-passed)
		(safety-check-passed)
		(= (time-elapsed) 0)
		(= (doses) 0)
		(= (max-doses-in-one-day) 4)
		(= (half-life) 180.0)
		(= (dose-amount) 1000.0)
		(= (gap-between-doses) 240.0)
		(= (pr) 300.00)
		(= (max-pr) 3000.0)
		(= (min-pr) 150.0)
		(at 1280 (end-of-day))
	)
	(:goal
		(and
			(min-check-passed)
			(>= (doses) 1)
			(<= (doses) (max-doses-in-one-day))
			(end-of-day)
		)
	)
)
